version: 2
jobs:
  build:
    docker:
      - image: maxmcd/webtty-node-go:no-libssl
    working_directory: /go/src/github.com/maxmcd/webtty
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Branch }}-{{ .Revision }}
            - v1-repo-{{ .Branch }}
            - v1-repo
      - checkout
      - run:
          name: run go tests
          command: |
            set -e
            export GO111MODULE=on
            go get -u golang.org/x/lint/golint
            go mod download
            golint -set_exit_status
            go test
            go test ./pkg/sd
      - run:
          name: run npm tests
          command: |
            set -e
            cd ./web-client
            npm install
            npm run build
            npm run test
      - save_cache:
          key: v1-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - /go/
